[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Low level IO"
edition = "2018"
name = "llio"
version = "0.1.0"

[dependencies]
heapless = "0.5"
log = "0.4"
log-server = {path = "../log-server"}
ticktimer-server = {path = "../ticktimer-server"}
xous = {path = "../../xous-rs"}
xous-ipc = {path = "../../xous-ipc"}
xous-names = {path = "../xous-names"}

[dependencies.rkyv]
default-features = false
features = ["const_generics"]
version = "0.4.1"

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[target.'cfg(any(windows,unix))'.dependencies]

[features]
debugprint = []
default = [] # "debugprint"
#default = ["debugprint"] # , "fccagent"
