[package]
name = "xous"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "System call interface for Xous"

[dependencies]
bitflags = "1"
xous-macros = { path = "../macros", version = "0.1.0" }

[features]
# If this is set, then the "Drop" feature of MemoryMessage structs
# will not be implemented.  This should only be set by the kernel.
forget-memory-messages = []

default = []

[target.'cfg(any(windows,unix))'.dependencies]
lazy_static = "1.4"
hex = "0.4"
