[package]
name = "xous"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "System call interface for Xous"

[dependencies]
bitflags = "1"
xous-macros = { path = "../macros", version = "0.1.0" }
log = { version = "0.4", optional = true }
rkyv = { version = "0.3.1", default_features = false }

[features]
# If this is set, then the "Drop" feature of MemoryMessage structs
# will not be implemented.  This should only be set by the kernel.
forget-memory-messages = []

# `logging` causes this program to connect to a log server on startup
# so you can run log commands such as `info!()`.
logging = ["log"]

default = []

[target.'cfg(any(windows,unix))'.dependencies]
lazy_static = "1.4"
hex = "0.4"
# debug-here = "*"
