[package]
name = "xous"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "System call interface for Xous"

[dependencies]
bitflags = "1.2.1"

[features]
# If this is set, then the "Drop" feature of MemoryMessage structs
# will not be implemented.  This should only be set by the kernel.
forget-memory-messages = []

# If this is set, create_process() will instead create a thread in
# the current process. This is used by the test suite.
processes-as-threads = []

default = []

[target.'cfg(any(windows,unix))'.dependencies]
lazy_static = "1.4"
hex = "0.4"
