[package]
name = "ticktimer-server"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Provide high-resolution, non-rollover system time"

[dependencies]
xous = { path = "../../xous-rs" }
embedded-graphics = "0.6"

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}
