[workspace]
members = [
    "xous-rs",
    "tools",
    "macros",
    "examples/shell",
    "examples/graphics-server",
    "examples/log-server",
    "xtask",
    "utra/utra"
]
default-members = [
    "examples/shell",
    "examples/log-server",
    "examples/graphics-server",
]

# These packages have custom RUSTFLAGS, so if they
# were included in the workspace they would cause
# packages to be rebuilt every time they were touched.
# Keep them out of the main workspace.
exclude = [
    "kernel",
    "loader",
]

[profile.release]
codegen-units = 1 # 1 better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = "thin"
