[workspace]
members = [
    "kernel",
    "loader",
    "tools",
    "xous-rs",
    "macros",
    "examples/shell",
    "examples/graphics",
    "examples/log",
]
default-members = ["examples/shell", "examples/log", "examples/graphics"]

[profile.release]
codegen-units = 1 # 1 better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true
