[workspace]
default-members = [
  "services/log-server",
  "services/graphics-server",
  "services/ticktimer-server",
  "services/xous-names",
  "services/keyboard",
  "services/com",
  "services/trng",
  "services/gam",
  "imports/blitstr-ref",
  "imports/com_rs-ref",
  "services/ime-plugin-api",
  "services/benchmark",
  "services/benchmark-target",
  "services/ime-frontend",
  "services/ime-plugin-shell",
  "services/content-plugin-api",
  "services/shellchat",
  "services/llio",
  "services/rtc",
  "services/cb-test-srv",
  "services/cb-test-c1",
  "services/cb-test-c2",
  "services/susres",
  "services/codec",
  "services/engine-sha512",
  "services/engine-25519",
  "services/aes",
]
members = [
  "xous-ipc",
  "xous-rs",
  "tools",
  "macros",
  "services/aes-test",
  "services/graphics-server",
  "services/log-server",
  "services/ticktimer-server",
  "services/com",
  "services/xous-names",
  "services/keyboard",
  "services/kernel-test",
  "services/trng",
  "services/gam",
  "services/benchmark",
  "services/benchmark-target",
  "services/ime-frontend",
  "services/ime-plugin-shell",
  "services/rkyv-test-server",
  "services/rkyv-test-client",
  "services/shellchat",
  "svd2repl",
  "svd2utra",
  "xtask",
  "imports/blitstr-ref",
  "imports/com_rs-ref",
  "services/ime-plugin-api",
  "services/content-plugin-api",
  "services/llio",
  "services/rtc",
  "services/cb-test-srv",
  "services/cb-test-c1",
  "services/cb-test-c2",
  "services/susres",
  "services/codec",
  "services/engine-sha512",
  "services/engine-25519",
  "services/aes",
]
resolver = "2"

# These packages have custom RUSTFLAGS, so if they
# were included in the workspace they would cause
# packages to be rebuilt every time they were touched.
# Keep them out of the main workspace.
exclude = [
  "kernel",
  "loader", # Exclude UTRA, since it is machine-generated.
  "utralib",
]

[profile.release]
codegen-units = 1 # 1 better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = "fat"
#panic = "abort" # Remove panic output, which can reduce file size
#opt-level = 'z'  # Optimize for size instead of performance

[patch.crates-io]
xous = {path = "xous-rs"}
xous-macros = {path = "macros"}
