[workspace]
resolver = "2"
members = [
    "xous-rs",
    "tools",
    "macros",
    "services/shell",
    "services/graphics-server",
    "services/log-server",
    "services/ticktimer-server",
    "services/com",
    "services/llio",
    "services/trng-tester",
    "services/fcc-agent",
    "services/xous-names",
    "services/keyboard",
    "services/kernel-test",
    "services/trng",
    "services/gam",
    "services/benchmark",
    "services/benchmark-target",
    "services/ime-frontend",
    "services/ime-plugin-shell",
    "svd2utra",
    "xtask",
    "imports/blitstr-ref",
    "imports/com_rs-ref",
    "services/ime-plugin-api",
]
default-members = [
    "services/shell",
    "services/log-server",
    "services/graphics-server",
    "services/ticktimer-server",
    "services/trng-tester",
    "services/fcc-agent",
    "services/xous-names",
    "services/keyboard",
    "services/com",
    "services/llio",
    "services/trng",
    "services/gam",
    "imports/blitstr-ref",
    "imports/com_rs-ref",
    "services/ime-plugin-api",
    "services/benchmark",
    "services/benchmark-target",
    "services/ime-frontend",
    "services/ime-plugin-shell",
]

# These packages have custom RUSTFLAGS, so if they
# were included in the workspace they would cause
# packages to be rebuilt every time they were touched.
# Keep them out of the main workspace.
exclude = [
    "kernel",
    "loader",

    # Exclude UTRA, since it is machine-generated.
    "utralib",
]

[profile.release]
codegen-units = 1 # 1 better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = "fat"

