[workspace]
members = [
    "xous-rs",
    "tools",
    "macros",
    "services/shell",
    "services/graphics-server",
    "services/log-server",
    "services/ticktimer-server",
    "services/com",
#    "services/xous-names",
    "svd2utra",
    "xtask",
]
default-members = [
    "services/shell",
    "services/log-server",
    "services/graphics-server",
    "services/ticktimer-server",
#    "services/xous-names",
    "services/com",
]

# These packages have custom RUSTFLAGS, so if they
# were included in the workspace they would cause
# packages to be rebuilt every time they were touched.
# Keep them out of the main workspace.
exclude = [
    "kernel",
    "loader",

    # Exclude UTRA, since it is machine-generated.
    "utralib",
]

[profile.release]
codegen-units = 1 # 1 better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = "fat"
