# if you want to format 'em, then you maintain 'em!
ignore = [
  "services/graphics-server",
  "services/com",
  "services/keyboard",
  "services/gam",
  "services/status",
  "services/ime-frontend",
  "services/ime-plugin-shell",
  "services/shellchat",
  "services/ime-plugin-api",
  "services/content-plugin-api",
  "services/llio",
  "services/rtc",
  "services/susres",
  "services/codec",
  "services/engine-sha512",
  "services/engine-25519",
  "services/aes",
  "services/spinor",
  "services/root-keys",
  "services/jtag",
]
