ignore = [
  "services/aes-test",
  "services/graphics-server",
  "services/log-server",
  "services/ticktimer-server",
  "services/com",
  "services/xous-names",
  "services/keyboard",
  "services/trng",
  "services/gam",
  "services/status",
  "services/benchmark",
  "services/benchmark-target",
  "services/ime-frontend",
  "services/ime-plugin-shell",
  "services/shellchat",
  "imports/blitstr-ref",
  "imports/com_rs-ref",
  "services/ime-plugin-api",
  "services/content-plugin-api",
  "services/llio",
  "services/rtc",
  "services/susres",
  "services/codec",
  "services/engine-sha512",
  "services/engine-25519",
  "services/aes",
  "services/spinor",
  "services/root-keys",
  "services/jtag",
]
