[package]
name = "net"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Network middleware"

# Dependency policy: fully specify dependencies to the minor version number
[dependencies]
xous = { path = "../../xous-rs" }
xous-ipc = {path="../../xous-ipc"}
log-server = { path = "../log-server" }
ticktimer-server = { path = "../ticktimer-server" }
xous-names = { path = "../xous-names" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
susres = {path = "../susres"}
#rkyv = "0.7.18"
rkyv = {version = "0.4.3", features = ["const_generics"], default-features = false}
llio = {path = "../llio"}
com = {path = "../com"}
byteorder = { version = "1.0", default-features = false }
trng = {path = "../trng"}
com_rs-ref = {path = "../../imports/com_rs-ref"}
modals = {path = "../modals"}
locales = {path = "../../locales"}

# for automatic SSID management and AP list storage
pddb = {path = "../pddb"}

[dependencies.smoltcp]
# smoltcp 0.8.0 mainline has a bug in ICMPv4. This git rev patches over it until the maintainers can
# confirm a proper patch for the issue.
#git = "https://github.com/smoltcp-rs/smoltcp.git"
git = "https://github.com/betrusted-io/smoltcp.git"
rev = "35c8ec3d30c846442a1faae01fb0537641aef898"

# note: maintainer suggests maybe we should use commit d05ebdd88f7f2b87a2ffe3256a42f67809d2d7e4 on mainline
# see https://github.com/smoltcp-rs/smoltcp/issues/613

# path = "../../../smoltcp"
default-features = false
features = [
  "std", "log", # needed for `cargo test --no-default-features --features default` :/
  "medium-ethernet", "medium-ip",
  "phy-raw_socket",
  "proto-ipv4", "proto-ipv6",
  "socket-raw", "socket-icmp", "socket-udp", "socket-tcp",
]
#features = ["verbose"]
#version = "0.7.5"
#features = ["proto-ipv4"]


[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[features]
renode-minimal = []
default = []
