[package]
name = "websocket"
version = "0.0.0"
authors = ["nhoj <john@nhoj.info>"]
edition = "2018"
description = "Xous Websocket service"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
