[package]
name = "ctap-crypto"
version = "0.1.0"
authors = [
  "Fabian Kaczmarczyck <kaczmarczyck@google.com>",
  "Guillaume Endignoux <guillaumee@google.com>",
  "Jean-Michel Picod <jmichel@google.com>",
]
license = "Apache-2.0"
edition = "2018"

[dependencies]
cbor = { path = "../cbor" }
arrayref = "0.3.6"
subtle = { version = "2.2.3", default-features = false}
trng = {path = "../../../../services/trng"}
xous-names = {path = "../../../../services/xous-names"}
rand_core = "0.5.1"
#p256 = {version = "0.11.0", default-features = false, features = ["ecdsa", "ecdh", "std"]}
