[package]
name = "xtask"
description = "Cargo-based build system for Xous"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"

# Dependency policy: fully specify dependencies to the minor version number
[dependencies]
curl = "0.4.35"
atty = "0.2.14"
filetime = "0.2.14"
rustc_version = "0.4.0"
zip = "0.5.13"

[build-dependencies]
vergen = "3.2.0"
filetime = "0.2.14"
