[package]
name = "xtask"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#"ed25519-dalek" = "1"
#"pem" = "0.8"

# locales generation
glob = "0.3.0"
quote = "1.0.2"
serde_json = "1.0.41"
proc-macro2 = "1.0"
regex = "1.3.1"
lazy_static = "1.4.0"