[package]
name = "xtask"
description = "Cargo-based build system for Xous"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"

[dependencies]
curl = "0.4"
atty = "0.2"
filetime = "0.2"
rustc_version = "0.4"
zip = "0.5"