[package]
name = "log-server"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "Log output program"

[dependencies]
xous = { path = "../../xous-rs" }

#[target.'cfg(any(windows, unix))'.dependencies]
#pancurses = "*"


[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[features]
debugprint = []
default = [] # "debugprint"
