[package]
authors = ["Sean Cross <sean@xobs.io>"]
description = "Log output program"
edition = "2018"
name = "log-server"
version = "0.1.0"

# Dependency policy: nail down all dependencies to the minor version number, so that changes to the code base are deliberate acts.
[dependencies]
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
xous = {path = "../../xous-rs"}
xous-ipc = {path = "../../xous-ipc"}

[build-dependencies]
vergen = "3"

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[features]
debugprint = [] # adding this allocates the UART for debugging the logger
logging = [] # adding this allocates the hardware UART for console interactions
#default = []
default = ["logging"]
# default = ["debugprint", "logging"]
