[package]
name = "log-server"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "Log output program"

[dependencies]
xous = { path = "../../xous-rs" }
log = "0.4"

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[features]
debugprint = []  # adding this allocates the UART for debugging the logger
logging = []  # adding this allocates the UART for logging of Xous
#default = []
default = ["logging"]
#default = ["debugprint"]
