[package]
name = "kernel"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "Core kernel for Xous, including task switching and memory management"

[dependencies]
bitflags = "1.2.1"
xous = { path = "../xous-rs", features = ["forget-memory-messages"] }
debug-here = "0.2.2"
stats_alloc = { version = "0.1.8", optional = true }

[target.'cfg(target_arch = "riscv32")'.dependencies]
riscv = "0.5.6"

[dependencies.sha3]
default-features = false
version = "0.8.2"

[target.'cfg(windows)'.dependencies]
lazy_static = "1.4"

[target.'cfg(unix)'.dependencies]
lazy_static = "1.4"

[features]
debug-print = []
report-memory = ["stats_alloc"]

[target.'cfg(any(windows, unix))'.dependencies]
rand = "0.7"
