[package]
name = "kernel"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "Core kernel for Xous, including task switching and memory management"

[dependencies]
bitflags = "1.2.1"
riscv = { git = "https://github.com/rust-embedded/riscv.git", rev = "30af64cad7b3869a14182ab18b48ad0c71cce1ed" }
xous = { path = "../xous-rs" }

[features]
debug-print = []
