[package]
name = "kernel"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "Core kernel for Xous, including task switching and memory management"

[dependencies]
bitflags = "1.2.1"
riscv = "0.5.6"
xous = { path = "../xous-rs", features = ["forget-memory-messages"] }

[dependencies.sha3]
default-features = false
version = "0.8.2"

[features]
debug-print = []
