[package]
name = "kernel"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "Core kernel for Xous, including task switching and memory management"

[dependencies]
bitflags = "1.2.1"
xous-kernel = { package = "xous", path = "../xous-rs", features = ["forget-memory-messages"] }
stats_alloc = { version = "0.1.8", optional = true }
sha3 = { default-features = false, version = "0.8.2" }

[target.'cfg(target_arch = "riscv32")'.dependencies]
riscv = "0.5.6"

[features]
debug-print = []
report-memory = ["stats_alloc"]

[target.'cfg(any(windows, unix))'.dependencies]
lazy_static = "1.4"
rand = "0.7"
hex = "0.4"
debug-here = "0.2.2"

[profile.release]
codegen-units = 1 # 1 better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = thin
force-frame-pointers = no
