[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Manage keyboard input"
edition = "2018"
name = "keyboard"
version = "0.1.0"

[dependencies]
log = {version = "0.4", features = ["max_level_trace", "release_max_level_trace"]}
log-server = {path = "../log-server"}
ticktimer-server = {path = "../ticktimer-server"}
xous = {path = "../../xous-rs"}
xous-ipc = {path = "../../xous-ipc"}
xous-names = {path = "../xous-names"}

heapless = "0.5.6"

num-derive = {version = "0.3", default-features = false}
num-traits = {version = "0.2", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[features]
debugprint = []
default = [] # "debugprint"
