[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Provide high-resolution, non-rollover system time"
edition = "2018"
name = "ticktimer-server"
version = "0.1.0"

# Dependency policy: nail down all dependencies to the minor version number, so that changes to the code base are deliberate acts.
[dependencies]
log = "0.4.14"
log-server = {path = "../log-server"}
xous = {path = "../../xous-rs"}
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
susres = {path = "../susres"}
xous-names = {path = "../xous-names"}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[target.'cfg(any(windows,unix))'.dependencies]

[features]
debug-print = []
watchdog = []
# generally you want to disable watchdog if you're doing development
default = ["watchdog"]
# default = []
# default = ["debug-print"]
