[package]
name = "ticktimer-server"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Provide high-resolution, non-rollover system time"

[dependencies]
xous = { path = "../../xous-rs" }
heapless = "0.5"
log-server = { path = "../log-server" }
log = "0.4"

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[target.'cfg(any(windows,unix))'.dependencies]

[features]
debugprint = []
disablewatchdog = []
# generally you want to disable watchdog if you're doing development.
default = ["disablewatchdog"] # "debugprint"
