[package]
name = "cb-test-srv"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Callback test server"

[dependencies]
xous = { path = "../../xous-rs" }
ticktimer-server = { path = "../ticktimer-server" }
xous-names = { path = "../xous-names" }
log-server = { path = "../log-server" }
log = "0.4.14"
benchmark-target = { path = "../benchmark-target" }

xous-ipc = {path = "../../xous-ipc"}
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[target.'cfg(any(windows,unix))'.dependencies]

[features]
default = []
