[package]
name = "root-keys"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Xous root keys server"

[dependencies]
xous = { path = "../../xous-rs" }
log-server = { path = "../log-server" }
ticktimer-server = { path = "../ticktimer-server" }
xous-names = { path = "../xous-names" }
log = "0.4"
susres = {path = "../susres"}
trng = {path= "../trng"}

xous-ipc = {path = "../../xous-ipc"}
num-derive = {version = "0.3", default-features = false}
num-traits = {version = "0.2", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

cipher = "0.3"
blowfish = { version = "0.8", features = ["bcrypt"] }

gam = {path = "../gam"} # for direct password modals
locales = {path = "../../locales"}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[features]
default = []

[lib]
test = true

[[bin]]
name = "root-keys"
test = false