[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Graphical Abstraction Manager for Xous"
edition = "2018"
name = "gam"
version = "0.1.0"

[dependencies]
bitflags = "1.2.1"
blitstr-ref = {path = "../../imports/blitstr-ref"}
com = {path = "../com"}
content-plugin-api = {path = "../content-plugin-api"}
graphics-server = {path = "../graphics-server"}
heapless = "0.5"
ime-plugin-api = {path = "../ime-plugin-api"}
keyboard = {path = "../keyboard"}
log = "0.4"
log-server = {path = "../log-server"}
ticktimer-server = {path = "../ticktimer-server"}
trng = {path = "../trng"}
xous = {path = "../../xous-rs"}
xous-ipc = {path = "../../xous-ipc"}
xous-names = {path = "../xous-names"}

[dependencies.rkyv]
default-features = false
features = ["const_generics"]
version = "0.4.1"

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[features]
debugprint = []
# default = ["debugprint"] # "debugprint"
default = []
