[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Graphical Abstraction Manager for Xous"
edition = "2018"
name = "gam"
version = "0.1.0"

[dependencies]
bitflags = "1.2.1"
blitstr-ref = {path = "../../imports/blitstr-ref"}
com = {path = "../com"}
content-plugin-api = {path = "../content-plugin-api"}
graphics-server = {path = "../graphics-server"}
heapless = "0.7"
ime-plugin-api = {path = "../ime-plugin-api"}
keyboard = {path = "../keyboard"}
log = "0.4"
log-server = {path = "../log-server"}
ticktimer-server = {path = "../ticktimer-server"}
trng = {path = "../trng"}
rtc = {path = "../rtc"}
llio = {path = "../llio"}
xous = {path = "../../xous-rs"}
xous-ipc = {path = "../../xous-ipc"}
xous-names = {path = "../xous-names"}

num-derive = {version = "0.3", default-features = false}
num-traits = {version = "0.2", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

# short circuit the datetime call on hosted mode
[target.'cfg(any(windows,unix))'.dependencies]
chrono = "0.4"

[features]
debugprint = []
slowstatus = [] # used for braille mode, so console isn't overwhelmed with status
# default = ["debugprint"] # "debugprint"
default = []
