[package]
name = "gam"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Graphical Abstraction Manager for Xous"

[dependencies]
bitflags = "1.2.1"
xous = { path = "../../xous-rs" }
rkyv = { version = "0.3.1", default_features = false }
graphics-server = { path = "../graphics-server" }
ticktimer-server = { path = "../ticktimer-server" }
xous-names = { path = "../xous-names" }
log-server = { path = "../log-server" }
keyboard = { path = "../keyboard" }
trng = { path = "../trng" }
heapless = "0.5"
log = "0.4"
com = { path = "../com"}
blitstr-ref = { path = "../../imports/blitstr-ref" }
ime-frontend = {path="../ime-frontend"}


[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[features]
debugprint = []
# default = ["debugprint"] # "debugprint"
default = []
