[package]
name = "loader"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "Initial kernel loader for Xous"

# Dependency policy: fully specify dependencies to the minor version number
[dependencies]
utralib = { path = "utralib" }

[dependencies.com_rs]
git = "https://github.com/betrusted-io/com_rs"
branch = "main"

[dependencies.curve25519-dalek]
package = "curve25519-dalek"
version = "3.1.0"
default-features = false
features = ["u32e_backend"]

[dependencies.ed25519-dalek]
version = "1.0.1"
default-features = false
#features = ["u32_backend"]

[dev-dependencies]
lazy_static = "1.4.0"

[features]
debug-print = []
earlyprintk = []
#default = ["debug-print"]
default = []

[target.'cfg(not(any(windows, unix)))'.dependencies]
utralib = { path = "utralib" }

# patch key references into our local name space
[patch.crates-io.sha2]
path = "./sha2"
package = "sha2"
#default-features = false

[patch.crates-io.utralib]
path = "utralib"

[patch.crates-io.curve25519-dalek]
git = "https://github.com/betrusted-io/curve25519-dalek.git"
branch = "main"

[profile.release]
codegen-units = 1 # 1 better optimizations
debug = true      # symbols are nice and they don't increase the size on Flash
lto = "fat"
