[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = ""
edition = "2018"
name = "xous-names"
version = "0.1.0"

[dependencies]
hash32 = "0.2"
hash32-derive = "0.1.0"
num-derive = {version = "0.3", default-features = false}
num-traits = {version = "0.2", default-features = false}
log = "0.4"
log-server = {path = "../log-server"}
xous = {path = "../../xous-rs"}
xous-ipc = {path = "../../xous-ipc"}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[target.'cfg(any(windows,unix))'.dependencies]

[features]
debugprint = []
default = [] # "debugprint"
