[package]
authors = ["Sean Cross <sean@xobs.io>"]
description = "Manage the video output"
edition = "2018"
name = "graphics-server"
version = "0.1.0"

[dependencies]
blitstr-ref = {path = "../../imports/blitstr-ref"}
keyboard = {path = "../keyboard"}
log = "0.4"
log-server = {path = "../log-server"}
xous = {path = "../../xous-rs"}
susres = {path = "../susres"}
trng = {path = "../trng"}
ticktimer-server = {path = "../ticktimer-server"}

xous-ipc = {path = "../../xous-ipc"}
xous-names = {path = "../xous-names"}
num-derive = {version = "0.3", default-features = false}
num-traits = {version = "0.2", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[target.'cfg(any(windows,unix))'.dependencies]
minifb = {version = "0.19.2", git = "https://github.com/xobs/rust_minifb.git", rev = "ea25c2e4843abd130d6794b2045812907a24eab2"}

[features]
debugprint = []
braille = []
default = [] # "debugprint"
