[package]
authors = ["Sean Cross <sean@xobs.io>"]
description = "Manage the video output"
edition = "2018"
name = "graphics-server"
version = "0.1.0"

# Dependency policy: fully specify dependencies to the minor version number
[dependencies]
keyboard = {path = "../keyboard"}
log = "0.4.14"
log-server = {path = "../log-server"}
xous = {path = "../../xous-rs"}
susres = {path = "../susres"}
trng = {path = "../trng"}
ticktimer-server = {path = "../ticktimer-server"}

xous-ipc = {path = "../../xous-ipc"}
xous-names = {path = "../xous-names"}
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[target.'cfg(any(windows,unix))'.dependencies]
# this is forked from minifb because the `set_key_state` callback was dropped in later versions of minifb (or maybe it was never there?)
# the working branch is thus `set-key-state-cb`
minifb = {version = "0.19.2", git = "https://github.com/xobs/rust_minifb.git", rev = "1717ec60830c1f9592b77ce875e492afef1aa533"}

[features]
debugprint = []
braille = []
testing = []
default = []
