[package]
authors = ["Sean Cross <sean@xobs.io>"]
description = "Manage the video output"
edition = "2018"
name = "graphics-server"
version = "0.1.0"

[dependencies]
blitstr-ref = {path = "../../imports/blitstr-ref"}
hash32 = "0.1.0"
hash32-derive = "0.1.0"
keyboard = {path = "../keyboard"}
log = "0.4"
log-server = {path = "../log-server"}
xous = {path = "../../xous-rs"}
rkyv = { version = "0.3.1", default_features = false }
xous-names = {path = "../xous-names"}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[target.'cfg(any(windows,unix))'.dependencies]
minifb = {version = "0.19.2", git = "https://github.com/xobs/rust_minifb.git", rev = "bbbfc07c059919fae700fabe771346a001226dbc"}

[features]
debugprint = []
default = [] # "debugprint"
