[package]
name = "graphics-server"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "Manage the video output"

[dependencies]
xous = { path = "../../xous-rs" }
log-server = { path = "../log-server" }
xous-names = { path = "../xous-names" }
log = "0.4"
keyboard = { path = "../keyboard" }
hash32 = "0.1.0"
hash32-derive = "0.1.0"
blitstr-ref = { path = "../../imports/blitstr-ref" }

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[target.'cfg(any(windows,unix))'.dependencies]
minifb = "0.17"

[features]
debugprint = []
default = [] # "debugprint"
