[package]
name = "graphics-server"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "Manage the video output"

[dependencies]
xous = { path = "../../xous-rs" }

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[target.'cfg(any(windows,unix))'.dependencies]
minifb = "0.17"

[features]
debugprint = []
default = [] # "debugprint"
