[package]
name = "shell"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "Shell test program"

[dependencies]
bitflags = "1.2.1"
xous = { path = "../../xous-rs" }
graphics-server = { path = "../graphics-server" }

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}
