[package]
name = "graphics-server"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "Manage the video output"

[dependencies]
xous = { path = "../../xous-rs" }
embedded-graphics = "0.6"

[target.'cfg(not(any(windows,unix)))'.dependencies]
utra = { path = "../../utra"}

[target.'cfg(any(windows,unix))'.dependencies]
minifb = "0.17"
