[package]
name = "com_rs-ref"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "com_rs import package"

[dependencies]
com_rs = { git = "https://github.com/betrusted-io/com_rs.git", rev = "ebbe15a5285cc4b9de7edf279949f034e82709dd" }
#com_rs = { path = "../../../betrusted-ec/sw/com_rs" }


# targeting hardware
[target.'cfg(not(any(windows,unix)))'.dependencies]


# targeting hosted mode
[target.'cfg(any(windows,unix))'.dependencies]


[features]
default = []
