[package]
name = "blitstr-ref"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "blitstr import package"

[dependencies]
blitstr = { git = "https://github.com/betrusted-io/blitstr.git", rev = "cde0deb6784c3f5c7b9da838ea9aa14ed373bcb3" }
# blitstr = { path = "../../../blitstr" }


# targeting hardware
[target.'cfg(not(any(windows,unix)))'.dependencies]


# targeting hosted mode
[target.'cfg(any(windows,unix))'.dependencies]


[features]
default = []
