[package]
name = "blitstr-ref"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "blitstr import package"

[dependencies]
blitstr = { git = "https://github.com/betrusted-io/blitstr.git", rev = "216422d5b57af7464970552cc384a24cf5e1d782" }
#blitstr = { path = "../../../blitstr" }


# targeting hardware
[target.'cfg(not(any(windows,unix)))'.dependencies]


# targeting hosted mode
[target.'cfg(any(windows,unix))'.dependencies]


[features]
default = []
