[package]
name = "blitstr-ref"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "blitstr import package"

[dependencies]
blitstr = { git = "https://github.com/betrusted-io/blitstr.git", rev = "cebcabb9a2b0686bb47f6e1508640941ae88469c" }
# blitstr = { path = "../blitstr" }

# targeting hardware
[target.'cfg(not(any(windows,unix)))'.dependencies]

# targeting hosted mode
[target.'cfg(any(windows,unix))'.dependencies]

[features]
default = []
