[package]
name = "blitstr-ref"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "blitstr import package"

# Dependency policy: nail down all dependencies to the minor version number, so that changes to the code base are deliberate acts.
[dependencies]
blitstr = { git = "https://github.com/betrusted-io/blitstr.git", rev = "89675bf468fa51baaf0de94e806b85c92466ae64" }
# blitstr = { path = "../blitstr" }

# targeting hardware
[target.'cfg(not(any(windows,unix)))'.dependencies]

# targeting hosted mode
[target.'cfg(any(windows,unix))'.dependencies]

[features]
default = []
