[package]
name = "ime-plugin-shell"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "IME Shell Plugin"

[dependencies]
xous = { path = "../../xous-rs" }
heapless = "0.5.6"
log-server = { path = "../log-server" }
ticktimer-server = { path = "../ticktimer-server" }
xous-names = { path = "../xous-names" }
log = "0.4"
ime-plugin-api = {path="../ime-plugin-api"}

[dependencies.rkyv]
version = "0.4.1"
default-features = false
features = ["const_generics"]

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[features]
debugprint = []
default = [] # "debugprint"
