[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "IME Shell Plugin"
edition = "2018"
name = "ime-plugin-shell"
version = "0.1.0"

[dependencies]
heapless = "0.7"
ime-plugin-api = {path = "../ime-plugin-api"}
log = "0.4"
log-server = {path = "../log-server"}
ticktimer-server = {path = "../ticktimer-server"}
xous = {path = "../../xous-rs"}
xous-ipc = {path = "../../xous-ipc"}
xous-names = {path = "../xous-names"}

num-derive = {version = "0.3", default-features = false}
num-traits = {version = "0.2", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[features]
debugprint = []
default = [] # "debugprint"
