[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "A shell with a chat-like interface"
edition = "2018"
name = "shellchat"
version = "0.1.0"

[dependencies]
com = {path = "../com"}
content-plugin-api = {path = "../content-plugin-api"}# all content canvas providers must provide this API
gam = {path = "../gam"}
graphics-server = {path = "../graphics-server"}
ime-plugin-api = {path = "../ime-plugin-api"}
ime-plugin-shell = {path = "../ime-plugin-shell"}
llio = {path = "../llio"}
rtc = {path = "../rtc"}
log = "0.4"
log-server = {path = "../log-server"}
ticktimer-server = {path = "../ticktimer-server"}
xous = {path = "../../xous-rs"}
xous-ipc = {path = "../../xous-ipc"}
xous-names = {path = "../xous-names"}
keyboard = {path = "../keyboard"}
susres = {path = "../susres"}
codec = {path = "../codec"}
engine-sha512 = {path="../engine-sha512"}
digest = "0.9"
aes-xous={path="../aes"}
cipher = "0.3"
engine-25519 = {path="../engine-25519"}

heapless = "0.7"
trng = {path = "../trng"}

num-derive = {version = "0.3", default-features = false}
num-traits = {version = "0.2", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

# for the curve25519 tests
# hardware acceleration adaptations are inserted into a fork of the main branch.
rand_core = "0.5"
hex = {version = "0.4.3", default-features = false, features = []}
[dependencies.curve25519-dalek]
git="https://github.com/betrusted-io/curve25519-dalek.git"
branch="main"
#path = "../../../curve25519-dalek"
default-features = false
features = ["u32_backend", "betrusted"]

[dependencies.x25519-dalek]
version = "1.1.1"
default-features = false
features = ["u32_backend"]

[dependencies.ed25519-dalek]
#version = "1.0.1"
path = "../../../ed25519-dalek"
default-features = false
features = ["u32_backend"]

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[features]
debugprint = []
default = [] # "debugprint"
