[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "A shell with a chat-like interface"
edition = "2018"
name = "shellchat"
version = "0.1.0"

[dependencies]
com = {path = "../com"}
content-plugin-api = {path = "../content-plugin-api"}# all content canvas providers must provide this API
gam = {path = "../gam"}
graphics-server = {path = "../graphics-server"}
heapless = "0.5.6"
ime-plugin-api = {path = "../ime-plugin-api"}
llio = {path = "../llio"}
log = "0.4"
log-server = {path = "../log-server"}
ticktimer-server = {path = "../ticktimer-server"}
xous = {path = "../../xous-rs"}
xous-ipc = {path = "../../xous-ipc"}
xous-names = {path = "../xous-names"}

[dependencies.rkyv]
default-features = false
features = ["const_generics"]
version = "0.4.1"

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[features]
debugprint = []
default = [] # "debugprint"
