[package]
name = "aes"
version = "0.7.5"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "AES library for Xous"

[dependencies]
xous = { path = "../../xous-rs" }
log-server = { path = "../log-server" }
log = "0.4.14"
cipher = "0.3.0"
ctr = { version = "0.7", optional = true }
opaque-debug = "0.3.0"
hex-literal = "0.3.1"
zeroize = "1.3.0"

[features]
compact = [] # Reduce code size at the cost of slower performance
default = []
