[package]
name = "trng-tester"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "TRNG tester"

[dependencies]
xous = { path = "../../xous-rs" }
heapless = "0.5"
log-server = { path = "../log-server" }
ticktimer-server = { path = "../ticktimer-server" }
log = "0.4"
typenum = "1.12"

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[target.'cfg(any(windows,unix))'.dependencies]

[features]
debugprint = []
default = [] # "debugprint"
#default = ["debugprint"]
