[package]
name = "utralib"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"

[features]
std = []

default_features = ["std"]

# Dependency policy: nail down all dependencies to the minor version number, so that changes to the code base are deliberate acts.
[dependencies]

[build-dependencies]
svd2utra = { path = "../svd2utra" }
